### ISSUE TITLE
GitHub Actionsでのrake taskがコケている

### ISSUE THREAD

**Issue by pocke** [rurema/doctree#2058]
https://github.com/rurema/doctree/pull/2057/checks?check_run_id=356121285

```
Tasks: TOP => default => check_format => statichtml => statichtml:2.6.0
(See full trace by running task with --trace)
mkdir -p /tmp/html/2.3.0
bundler: failed to load command: bitclust (/opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bin/bitclust)
Errno::ENOENT: No such file or directory @ realpath_rec - /home/runner/work/data
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bundler/gems/bitclust-f02e77604d9b/lib/bitclust/subcommands/statichtml_command.rb:120:in `realpath'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bundler/gems/bitclust-f02e77604d9b/lib/bitclust/subcommands/statichtml_command.rb:120:in `realpath'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bundler/gems/bitclust-f02e77604d9b/lib/bitclust/subcommands/statichtml_command.rb:120:in `block in initialize'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/2.6.0/optparse.rb:1582:in `block in parse_in_order'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/2.6.0/optparse.rb:1568:in `catch'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/2.6.0/optparse.rb:1568:in `parse_in_order'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/2.6.0/optparse.rb:1562:in `order!'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/2.6.0/optparse.rb:1656:in `permute!'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/2.6.0/optparse.rb:1678:in `parse!'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bundler/gems/bitclust-f02e77604d9b/lib/bitclust/subcommand.rb:23:in `parse'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bundler/gems/bitclust-f02e77604d9b/lib/bitclust/runner.rb:125:in `_run'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bundler/gems/bitclust-f02e77604d9b/lib/bitclust/runner.rb:32:in `run'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bundler/gems/bitclust-f02e77604d9b/bin/bitclust:14:in `<top (required)>'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bin/bitclust:23:in `load'
  /opt/hostedtoolcache/Ruby/2.6.3/x64/lib/ruby/gems/2.6.0/bin/bitclust:23:in `<top (required)>'
##[error]Process completed with exit code 1.
```

**Comment by hanachin** [comment]
multitask化の影響な気がしております

**Comment by S-H-GAMELINKS** [comment]
GitHub Actionで使用するbundlerのバージョンを2.1.0に指定するとこけなかったのでbundler側での話なのかもしれない

ref: https://hanachin.hateblo.jp/entry/2019/11/25/005501

**Comment by S-H-GAMELINKS** [comment]
GitHub Actionでは以下の環境で動作しててこけてるみたいでした。

`Ruby 2.6.3`
`bunlder 2.1.2`

ちなみに確認で手元のUbuntu 18.04でRubyとbundlerのバージョン合わせてタスク実行したらこけてました。

また、Ruby 2.6.5とbundler 2.1.2では問題なかったようなのでGitHub Actionで使用できるRubyのバージョンが上がれば解決できそうな感じでもありますねー

**Comment by pocke** [comment]
Resolved by #2064
