### ISSUE TITLE
bitclust htmlfile で doc 下のファイルを処理して HTML をファイルに保存しようとするとエラー

### ISSUE THREAD

**Issue by scivola** [rurema/doctree#929]
bitclust を使ってみようとしたのですが，うまくいきません。

まず

```
$ gem i refe2
$ git clone https://github.com/rurema/doctree.git
```

して，`bitclust htmlfile` で `doc` 内のファイルを HTML 化しようとしたのですが，なぜか `> a.html` とリダイレクトしようとするとエラーが出ます。`> a.html` をつけずにやると，正常に画面に HTML がだーっと表示されます。

```
$ cd doctree/refm/doc
$ bitclust htmlfile --ruby=2.4.0 help.rd > a.html
help.rd:1: not a constant: "プ"
/Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:153:in `isconst'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:147:in `parse_level1_header'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:114:in `block in read_classes'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/lineinput.rb:115:in `while_match'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:113:in `read_classes'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:99:in `do_parse'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:80:in `parse'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:73:in `block in parse_file'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/compat.rb:34:in `open'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/compat.rb:34:in `fopen'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:72:in `parse_file'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/rrdparser.rb:29:in `parse_stdlib_file'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/subcommands/htmlfile_command.rb:58:in `exec'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/runner.rb:140:in `_run'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/lib/bitclust/runner.rb:32:in `run'
	from /Users/XXXX/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bitclust-core-1.1.0/bin/bitclust:14:in `<top (required)>'
	from /Users/XXXX/.rbenv/versions/2.4.2/bin/bitclust:23:in `load'
	from /Users/XXXX/.rbenv/versions/2.4.2/bin/bitclust:23:in `<main>'
```

refm/doc/marshal_format.rd の場合はエラーが違い，

```
refm/doc/marshal_format.rd:1: not a constant: "フォーマット"
```

となりました。

以下の環境で再現しました。

macOS 10.11.6
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin15]

Windows 10
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

**Comment by scivola** [comment]
> `> a.html` をつけずにやると，正常に

の部分はどうも私の勘違いだったようです。
標準出力のリダイレクトがあろうがなかろうがエラーが出ます。

例外を出しているのは

https://github.com/rurema/bitclust/blob/83998a1e2f5e2d644ee046fbec24b09d85c79950/lib/bitclust/rrdparser.rb#L142-L156

の部分です。

要するに，

> `= class Array < Object`

みたいなレベル 1 ヘッダー行の

> `class Array < Object`

の部分に対して、正規表現

```rb
/\A(\S+)\s*([^\s<]+)(?:\s*<\s*(\S+))?\z/
```

で「`Array`」の部分を切り出し、この文字列が定数名として妥当かどうかを `isconst` メソッドで確認しているのですが，`refm/doc/help.rd` ファイルの場合、レベル 1 ヘッダーが

> `= このマニュアルのヘルプ`

であるため，クラス名として取り出した文字列が「プ」になって，エラーが出ているということですね。

エラーの原因は分かったのですが、`help.rd` を処理するにはどうすればいいのでしょうか？

**Comment by znz** [comment]
`\s*([^\s<]+)`
を
`(?:\s+([^\s<]+))?`
にすればいいのでは、と思ったのですが、
`refm/doc/symref.rd:= Rubyで使われる記号の意味（正規表現の複雑な記号は除く）`
のように doc 以下にスペースの入ったレベル 1 ヘッダー行もあるので、もうちょっと考える必要がありそうです。

`$1` のところを `class|reopen|...` のように並べるという手もありそうですが、その部分を typo したときに気付きにくくなりそう…。

**Comment by hanachin** [comment]
`doc` 以下のファイルの場合は以下のように `--force` オプションをつけるとうまく処理できそうです
```
% bitclust htmlfile --force --ruby=2.5.0 help.rd
% bitclust htmlfile --help
Usage: bitclust htmlfile [options] rdfile
        --target=NAME                Compile NAME to HTML.
    -f, --force                      Force to use rd_file template.
        --ruby_version, --ruby=VER   Set Ruby version
        --baseurl=URL                Base URL of generated HTML
        --templatedir=PATH           Template directory
    -h, --help                       Print this message and quit.
```
